# Generated by Django 6.1 on 2026-08-27 17:47

import apps.shops.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(default=apps.shops.models.generate_shop_id, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feature_config', serialize=False, to='shops.shop')),
                ('inventory', models.BooleanField(default=True)),
                ('sales', models.BooleanField(default=True)),
                ('customers', models.BooleanField(default=True)),
                ('reports', models.BooleanField(default=True)),
            ],
        ),
    ]
